"use client";
import { decorationWhatsapp } from "../../lib/decoration-contact";
import Link from "next/link";
import { useEffect, useState } from "react";
import { DecorationContent } from "../../lib/decorations";
import "./decorations.css";
type Design=DecorationContent & {id:string;featured:boolean;mobile:string};
export default function DecorationGallery(){const [designs,setDesigns]=useState<Design[]>([]);const [categories,setCategories]=useState<string[]>([]);const [category,setCategory]=useState("All");const [hall,setHall]=useState("All");const [message,setMessage]=useState("Loading decorations…");const [selected,setSelected]=useState<Design|null>(null);
useEffect(()=>{fetch("/api/decorations").then(async r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>{setDesigns(d.designs);setCategories(d.categories);setMessage("");}).catch(()=>setMessage("Unable to load decorations. Please try again."));},[]);
useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelected(null);};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[]);
const visible=designs.filter(d=>(category==="All"||d.category===category)&&(hall==="All"||d.hall==="Both"||d.hall===hall));
return <main className="decorationPage"><header className="decorHeader"><div><p className="kicker">Aishwarya Party Hall</p><h1>Stage Decorations</h1><p>Find a setting for your birthday, baby shower, reception and special celebration.</p></div><Link href="/">← Back to our halls</Link></header><div className="decorFilters"><label>Occasion<select value={category} onChange={e=>setCategory(e.target.value)}>{["All",...categories].map(c=><option key={c}>{c}</option>)}</select></label><label>Hall<select value={hall} onChange={e=>setHall(e.target.value)}>{["All","Padi","Korattur"].map(c=><option key={c}>{c}</option>)}</select></label></div>{message?<p role="status">{message}</p>:!visible.length?<section className="decorPanel"><h2>{designs.length?"No designs match these filters":"Decoration designs are coming soon"}</h2><p>Contact our team to discuss decoration options for your celebration.</p><p>Choose a published design to contact its decorator directly.</p></section>:<div className="decorGallery">{visible.map(d=><button className="decorCard" key={d.id} onClick={()=>setSelected(d)}><img src={d.photos[0]} alt={d.title} loading="lazy"/><div>{d.featured&&<small>Featured design</small>}<h2>{d.title}</h2><p>{d.category} · {d.hall==="Both"?"Padi & Korattur":d.hall}</p><p>{d.id} · Contact us for pricing</p><b>View design →</b></div></button>)}</div>}{selected&&<div className="decorOverlay" role="dialog" aria-modal="true" aria-label={selected.title}><section className="decorDetail"><button onClick={()=>setSelected(null)}>Close ×</button><h2>{selected.title}</h2><p>{selected.id} · {selected.category} · {selected.hall}</p>{selected.photos.map((photo,i)=><img src={photo} key={photo} alt={`${selected.title} — view ${i+1}`}/>)}<Link href={`/decorations/${selected.id}`}>Open design page →</Link><p>{selected.description}</p>{selected.included&&<><h3>What’s included</h3><p>{selected.included}</p></>}<p>Contact us for pricing. Final setup and availability are confirmed by our team.</p>{selected.mobile ? <><p>Decorator WhatsApp: +{selected.mobile}</p><a className="maroonButton" target="_blank" rel="noreferrer" href={decorationWhatsapp(selected.mobile,selected.id,selected.title)}>Enquire about this decoration</a></> : <p>The decorator’s WhatsApp number has not been added yet.</p>}</section></div>}</main>}
