"use client";

import { useState, type FormEvent } from 'react';
import { balance, deleteStaffRentRecord, paid, rentPaymentWindow, renewalReminderStart, validRecords, type Bill, type Hall, type Payment, type Records } from './model';
import './style.css';

import { useOnlineRecords } from './use-online-records';
const today = () => new Date().toISOString().slice(0, 10);
const uid = () => crypto.randomUUID();
const money = (amount: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Math.round(amount));
const displayDate = (value: string) => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${value}T00:00:00`)) : '—';
const Input = ({ name, label, type = 'text', value, required = true }: { name: string; label: string; type?: string; value?: string | number; required?: boolean }) => <label>{label}<input name={name} type={type} defaultValue={value} required={required} min={type === 'number' ? 0 : undefined} /></label>;

export function HallRentWorkspace() {
  const { data, ready, message, setMessage, save } = useOnlineRecords();
  const [tab, setTab] = useState('Halls');
  const [month, setMonth] = useState(today().slice(0, 7));
  const [selectedHall, setSelectedHall] = useState('');
  const [editingHall, setEditingHall] = useState<string | null>(null);
  const [receipt, setReceipt] = useState<Bill | null>(null);
  const date = today();




  const value = (form: FormData, name: string) => String(form.get(name) || '').trim();
  const number = (form: FormData, name: string) => Number(form.get(name) || 0);
  const submit = (event: FormEvent<HTMLFormElement>, action: (form: FormData) => boolean) => { event.preventDefault(); if (action(new FormData(event.currentTarget))) event.currentTarget.reset(); };
  const halls = data.halls;
  const rentBills = data.bills.filter(bill => bill.kind === 'Rent');
  const selected = halls.find(hall => hall.id === selectedHall) ?? null;
  const selectedBill = selected ? rentBills.find(bill => bill.entity === selected.id && bill.month === month) : null;
  const monthBills = rentBills.filter(bill => bill.month === month);

  function saveHall(form: FormData) {
    const hall: Hall = { id: editingHall ?? uid(), location: value(form, 'location'), address: value(form, 'address'), owner: value(form, 'owner'), phone: value(form, 'phone'), rent: number(form, 'rent'), deposit: number(form, 'deposit'), start: value(form, 'start'), renewal: value(form, 'renewal'), agreementNo: value(form, 'agreementNo'), agreementEnd: value(form, 'agreementEnd'), noticeDays: number(form, 'noticeDays'), dueDay: Math.min(28, Math.max(1, number(form, 'dueDay') || 5)), increaseType: value(form, 'increaseType'), increaseValue: number(form, 'increaseValue'), utilityNote: value(form, 'utilityNote'), bankDetails: value(form, 'bankDetails') };
    if (!hall.location || !hall.address || !hall.owner || !hall.start || !hall.renewal || hall.rent <= 0) { setMessage('Enter hall, owner, agreement dates and monthly rent.'); return false; }
    const next = editingHall ? { ...data, halls: data.halls.map(item => item.id === editingHall ? hall : item) } : { ...data, halls: [...data.halls, hall] };
    setEditingHall(null); return save(next, `${hall.location} hall details saved.`);
  }

  function createRent(form: FormData) {
    const hall = halls.find(item => item.id === value(form, 'hall'));
    const rent = number(form, 'rent'); const extra = number(form, 'extra');
    if (!hall || rent <= 0) { setMessage('Choose a hall and enter the rent due.'); return false; }
    const id = `Rent-${hall.id}-${month}`;
    if (data.bills.some(bill => bill.id === id)) { setMessage('Rent is already created for this hall and month. Use Payments to add split payments.'); return false; }
    const bill: Bill = { id, entity: hall.id, name: hall.location, location: hall.location, month, kind: 'Rent', basic: rent, leave: 0, recovery: 0, debit: 0, extra, total: Math.round(rent + extra), payments: [] };
    return save({ ...data, bills: [...data.bills, bill] }, `${hall.location} rent created for ${month}.`);
  }

  function recordPayment(form: FormData, bill: Bill) {
    const amount = number(form, 'amount'); const paymentDate = value(form, 'date');
    if (amount <= 0 || amount > balance(bill)) { setMessage('Payment must be above zero and within the rent balance.'); return false; }
    const payment: Payment = { id: uid(), date: paymentDate, amount, method: value(form, 'method'), reference: value(form, 'reference') };
    return save({ ...data, bills: data.bills.map(item => item.id === bill.id ? { ...item, payments: [...item.payments, payment] } : item) }, `${payment.method} payment recorded. Balance updated.`);
  }

  function exportBackup() { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `aishwarya-hall-rent-${today()}.json`; link.click(); URL.revokeObjectURL(link.href); }
  const reminders = halls.map(hall => { const { start: paymentStart, end: due } = rentPaymentWindow(month); const bill = rentBills.find(item => item.entity === hall.id && item.month === month); const renewal = hall.renewal; return { hall, paymentStart, due, bill, renewal, rentBalance: bill ? balance(bill) : hall.rent, renewalSoon: date >= renewalReminderStart(renewal) }; });

  if (!ready) return <main className="adminPage sr"><h1>Hall Rent</h1><p className="adminMessage">{message}</p></main>;
  const nav = [{ id: 'Halls', label: 'Hall Details' }, { id: 'Agreement', label: 'Agreement & Renewal' }, { id: 'Rent', label: 'Monthly Rent' }, { id: 'Payments', label: 'Payments' }, { id: 'Reminders', label: 'Rent Reminders' }, { id: 'Report', label: 'Rent Report' }, { id: 'Backup', label: 'Backup' }];
  return <main className="adminPage sr hall-rent"><div className="sr-screen"><header className="adminHeader"><div><p className="kicker">AISHWARYA PARTY HALL · ADMIN</p><h1>Hall Rent</h1><p>Agreement, renewal, monthly rent and split payment records.</p></div><a href="/admin">← Admin Home</a></header><div className="sr-toolbar"><label>Rent month<input type="month" value={month} onChange={event => setMonth(event.target.value)} /></label><span>Cash, Bank transfer, UPI and Cheque payments can be recorded separately for each rent month.</span></div><nav aria-label="Hall rent sections">{nav.map(item => <button key={item.id} aria-current={tab === item.id ? 'page' : undefined} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav>{message && <p className="adminMessage" role="status">{message}</p>}
    {tab === 'Halls' && <><section><h2>{editingHall ? 'Edit hall details' : 'Add Hall Details'}</h2><form key={editingHall ?? 'new'} onSubmit={event => submit(event, saveHall)}>{(() => { const hall = halls.find(item => item.id === editingHall); return <><Input name="location" label="Hall name / location" value={hall?.location}/><Input name="address" label="Hall address" value={hall?.address}/><Input name="owner" label="Owner / landlord name" value={hall?.owner}/><Input name="phone" label="Mobile number" value={hall?.phone} required={false}/><Input name="rent" label="Monthly rent ₹" type="number" value={hall?.rent}/><Input name="deposit" label="Security deposit ₹" type="number" value={hall?.deposit ?? 0} required={false}/><Input name="start" label="Agreement start" type="date" value={hall?.start}/><Input name="renewal" label="Renewal date" type="date" value={hall?.renewal}/><button>{editingHall ? 'Save changes' : 'Add Hall'}</button>{editingHall && <button type="button" onClick={() => setEditingHall(null)}>Cancel</button>}</>; })()}</form></section><section><h2>Saved halls</h2>{halls.length === 0 ? <p className="empty-state">Add your first hall to begin rent tracking.</p> : halls.map(hall => <article className="rent-hall-card" key={hall.id}><div><h3>{hall.location}</h3><p>{hall.address}</p><small>{hall.owner} · {hall.phone || 'No mobile number'}</small></div><div><small>Monthly rent</small><b>{money(hall.rent)}</b></div><div className="sr-actions"><button onClick={() => { setSelectedHall(hall.id); setTab('Rent'); }}>Monthly rent</button><button onClick={() => setEditingHall(hall.id)}>Edit</button><button className="sr-delete" onClick={() => { if (confirm(`Delete ${hall.location} and all of its rent records?`)) save(deleteStaffRentRecord(data, 'Rent', hall.id), `${hall.location} deleted.`); }}>Delete</button></div></article>)}</section></>}
    {tab === 'Agreement' && <section><h2>Agreement & Renewal</h2>{halls.length === 0 ? <p className="empty-state">Add hall details first.</p> : halls.map(hall => <form className="agreement-card" key={hall.id} onSubmit={event => submit(event, form => { const updated: Hall = { ...hall, agreementNo: value(form, 'agreementNo'), agreementEnd: value(form, 'agreementEnd'), noticeDays: number(form, 'noticeDays'), increaseType: value(form, 'increaseType'), increaseValue: number(form, 'increaseValue'), utilityNote: value(form, 'utilityNote'), bankDetails: value(form, 'bankDetails') }; return save({ ...data, halls: data.halls.map(item => item.id === hall.id ? updated : item) }, `${hall.location} agreement details saved.`); })}><div className="agreement-title"><h3>{hall.location}</h3><p>Agreement starts {displayDate(hall.start)} · Renewal {displayDate(hall.renewal)}</p></div><Input name="agreementNo" label="Agreement number" value={hall.agreementNo} required={false}/><Input name="agreementEnd" label="Agreement end" type="date" value={hall.agreementEnd || hall.renewal} required={false}/><Input name="noticeDays" label="Notice period days" type="number" value={hall.noticeDays ?? 30} required={false}/><label>Rent increase<select name="increaseType" defaultValue={hall.increaseType || 'None'}><option>None</option><option>Percentage</option><option>Fixed amount</option></select></label><Input name="increaseValue" label="Increase value" type="number" value={hall.increaseValue ?? 0} required={false}/><Input name="utilityNote" label="EB / maintenance note" value={hall.utilityNote} required={false}/><Input name="bankDetails" label="Bank / UPI details" value={hall.bankDetails} required={false}/><button>Save agreement</button></form>)}</section>}
    {tab === 'Rent' && <section><h2>Monthly Rent · {month}</h2><p>Create the rent due once for each hall. Extra charges can include EB, maintenance or GST.</p><form onSubmit={event => submit(event, createRent)}><label>Hall<select name="hall" value={selectedHall} onChange={event => setSelectedHall(event.target.value)} required><option value="">Choose hall</option>{halls.map(hall => <option key={hall.id} value={hall.id}>{hall.location}</option>)}</select></label><Input name="rent" label="Rent due ₹" type="number" value={selected?.rent}/><Input name="extra" label="Extra charges ₹" type="number" value={0} required={false}/><button>Create monthly rent</button></form>{selectedBill && <p className="sr-notice"><b>{selected?.location}</b> rent for {month} is {money(selectedBill.total)}. Paid: {money(paid(selectedBill))}. Balance: {money(balance(selectedBill))}.</p>}</section>}
    {tab === 'Payments' && <section className="payments-page"><div className="payments-heading"><div><p className="kicker">HALL RENT</p><h2>Monthly Rent Payments</h2><p>Record every Cash, Bank transfer, UPI or Cheque payment separately.</p></div></div>{monthBills.length === 0 ? <p className="empty-state">No rent created for {month}.</p> : <div className="payment-list">{monthBills.map(bill => <article className="payment-card" key={bill.id}><div className="payment-summary"><div><h3>{bill.name}</h3><p>Rent month {bill.month} · Due {money(bill.total)}</p></div><div className="payment-total"><span>Rent balance</span><b>{money(balance(bill))}</b></div><button onClick={() => setReceipt(bill)}>Receipt</button></div><div className="payment-stats"><span><small>Rent due</small><b>{money(bill.total)}</b></span><span><small>Total paid</small><b>{money(paid(bill))}</b></span><span><small>Status</small><b className={balance(bill) === 0 ? 'payment-settled' : 'payment-pending'}>{balance(bill) === 0 ? 'Paid' : 'Pending'}</b></span></div>{balance(bill) > 0 && <form className="payment-form" onSubmit={event => submit(event, form => recordPayment(form, bill))}><Input name="date" label="Payment date" type="date" value={date}/><Input name="amount" label="Payment amount ₹" type="number"/><label>Payment method<select name="method"><option>Cash</option><option>Bank transfer</option><option>UPI</option><option>Cheque</option></select></label><Input name="reference" label="Reference / receipt no." required={false}/><button>Record payment</button></form>}{bill.payments.length > 0 && <div className="payment-history">{bill.payments.map(payment => <p key={payment.id}><b>{displayDate(payment.date)}</b><span>{payment.method}</span><span>{payment.reference || '—'}</span><strong>{money(payment.amount)}</strong></p>)}</div>}</article>)}</div>}</section>}
    {tab === 'Reminders' && <section><h2>Rent & Renewal Reminders · {month}</h2><div className="reminder-list">{reminders.map(item => <article key={item.hall.id}><h3>{item.hall.location}</h3><p>Payment window: <b>{displayDate(item.paymentStart)} to {displayDate(item.due)}</b> · Balance: <strong>{money(item.rentBalance)}</strong></p><p>Renewal: <b>{displayDate(item.renewal)}</b>{date > item.renewal ? ' · Renewal overdue' : item.renewalSoon ? ' · Renewal due within one month' : ''}</p>{item.hall.noticeDays ? <small>Notice period: {item.hall.noticeDays} days</small> : null}</article>)}</div></section>}
    {tab === 'Report' && <section><h2>Rent Report</h2><div className="sr-cards"><article><span>Total rent created</span><strong>{money(rentBills.reduce((sum, bill) => sum + bill.total, 0))}</strong></article><article><span>Total paid</span><strong>{money(rentBills.reduce((sum, bill) => sum + paid(bill), 0))}</strong></article><article><span>Total balance</span><strong>{money(rentBills.reduce((sum, bill) => sum + balance(bill), 0))}</strong></article></div><div className="salary-report-table"><div className="salary-report-header"><span>Hall / month</span><span>Rent due</span><span>Paid</span><span>Balance</span><span></span></div>{[...rentBills].sort((a,b) => b.month.localeCompare(a.month)).map(bill => <div className="salary-report-row" key={bill.id}><span><b>{bill.name}</b><small>{bill.month}</small></span><span>{money(bill.total)}</span><span>{money(paid(bill))}</span><strong className={balance(bill) === 0 ? 'payment-settled' : 'payment-pending'}>{money(balance(bill))}</strong><button onClick={() => setReceipt(bill)}>Receipt</button></div>)}</div></section>}
    {tab === 'Backup' && <section><h2>Database backup</h2><p>Download a copy of the database records for safekeeping. It includes hall agreements, rent and split-payment records.</p><button onClick={exportBackup}>Download Backup</button><label className="restore">Restore backup<input type="file" accept="application/json,.json" onChange={async event => { const file = event.target.files?.[0]; if (!file) return; try { const restored = JSON.parse(await file.text()); if (!validRecords(restored)) throw Error(); if (confirm('Replace current records with this backup?')) save(restored, 'Backup restored.'); } catch { setMessage('This backup file is invalid.'); } event.target.value = ''; }} /></label></section>}
  </div>{receipt && <div className="rent-receipt"><div className="sr-toolbar sr-screen"><button onClick={() => window.print()}>Print / Save PDF</button><button onClick={() => setReceipt(null)}>Close</button></div><header><img src="/images/brand/aishwarya-party-hall-logo.jpg" alt="Aishwarya Party Hall logo"/><div><p>AISHWARYA PARTY HALL</p><h1>Rent Payment Receipt</h1><span>{receipt.name} · {receipt.month}</span></div></header><dl><div><dt>Monthly rent</dt><dd>{money(receipt.basic)}</dd></div><div><dt>Extra charges</dt><dd>{money(receipt.extra)}</dd></div><div><dt>Total rent due</dt><dd>{money(receipt.total)}</dd></div><div><dt>Total paid</dt><dd>{money(paid(receipt))}</dd></div><div className="balance-line"><dt>Rent balance</dt><dd>{money(balance(receipt))}</dd></div></dl><section><h3>Payment details</h3>{receipt.payments.map(payment => <p key={payment.id}>{displayDate(payment.date)} · {payment.method} · {payment.reference || 'No reference'} <b>{money(payment.amount)}</b></p>)}</section><footer>Generated {displayDate(date)} · Aishwarya Party Hall</footer></div>}</main>;
}
