"use client";
import { useEffect, useState, type FormEvent } from 'react';
import { advanceBalance, deleteStaffRentRecord, balance, emptyRecords, paid, salaryBill, validRecords, type Bill, type Records } from './model';
import './style.css';
const KEY = 'aph-staff-rent-v1';
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const money = (n: number) => new Intl.NumberFormat('en-IN', {style:'currency',currency:'INR'}).format(n);
const uid = () => crypto.randomUUID();
function Field({name,label,type='text',value,required=true}:{name:string;label:string;type?:string;value?:string|number;required?:boolean}) { return <label>{label}<input name={name} type={type} defaultValue={value} required={required} min={type==='number'?0:undefined} step={type==='number'?'0.01':undefined}/></label>; }
function Location({value}:{value?:string}){return <label>Location<select name="location" defaultValue={value}><option>Padi</option><option>Korattur</option></select></label>;}
export function StaffRentWorkspace({kind}:{kind:'Salary'|'Rent'}){
 const [editingId,setEditingId]=useState<string|null>(null);
 const isSalary=kind==='Salary';
 const title=isSalary?'Staff Salary':'Hall Rent';
 const tabs=isSalary?['Overview','Employees','Leave & Ledger','Payments','Backup']:['Overview','Hall Details','Payments','Backup'];
 const [data,setData]=useState<Records>(emptyRecords),[ready,setReady]=useState(false),[message,setMessage]=useState('Checking admin access…'),[month,setMonth]=useState(today().slice(0,7)),[tab,setTab]=useState('Overview'),[slip,setSlip]=useState<Bill|null>(null),[date,setDate]=useState(today());
 useEffect(()=>{ fetch('/api/auth/session').then(async r=>{if(!r.ok || (await r.json()).role!=='admin') throw Error('Sign in as an administrator to access salary records.');const saved=localStorage.getItem(KEY);if(saved){const parsed=JSON.parse(saved);if(!validRecords(parsed))throw Error("Saved data is invalid. Restore a valid backup before continuing.");setData(parsed);}setReady(true);setMessage('');}).catch(e=>setMessage(e.message));const timer=setInterval(()=>setDate(today()),60000);return ()=>clearInterval(timer);},[]);
 function save(next:Records){try{const latest=localStorage.getItem(KEY);if(latest&&JSON.stringify(JSON.parse(latest))!==JSON.stringify(data)){const updated=JSON.parse(latest);if(!validRecords(updated))throw Error();setData(updated);setMessage('Records changed in another page. Latest records loaded; please submit your change again.');return false;}localStorage.setItem(KEY,JSON.stringify(next));setData(next);setMessage('Saved on this browser.');return true;}catch{setMessage('Could not save. Export a backup and check browser storage.');return false;}}
 function removeRecord(id:string,name:string){
   const linkedBills=data.bills.filter(b=>b.kind===kind&&b.entity===id);
   const entries=kind==='Salary'?data.entries.filter(e=>e.employee===id).length:0;
   if(!confirm(`Delete ${name}? This also permanently deletes ${linkedBills.length} bill(s), ${linkedBills.reduce((n,b)=>n+b.payments.length,0)} payment(s) and ${entries} ledger entry/entries. Export a backup first if you need these records. This cannot be undone.`))return;
   if(save(deleteStaffRentRecord(data,kind,id))){setEditingId(null);setSlip(null);}
 }
 function form(event:FormEvent<HTMLFormElement>,action:(f:FormData)=>boolean){event.preventDefault();if(action(new FormData(event.currentTarget)))event.currentTarget.reset();}
 const str=(f:FormData,k:string)=>String(f.get(k)||'').trim();const num=(f:FormData,k:string)=>Number(f.get(k)||0);
 const drafts:Bill[]=[...data.employees.filter(e=>e.joined.slice(0,7)<=month).map(e=>salaryBill(data,e,month)),...data.halls.filter(h=>h.start.slice(0,7)<=month).map(h=>({id:`Rent-${h.id}-${month}`,entity:h.id,name:`${h.location} hall rent`,location:h.location,month,kind:'Rent',basic:h.rent,leave:0,recovery:0,debit:0,extra:0,total:h.rent,payments:[]}))].filter(b=>b.kind===kind&&!data.bills.some(x=>x.id===b.id));
 const bills=data.bills.filter(b=>b.kind===kind&&b.month===month);const outstanding=data.bills.filter(b=>b.kind===kind&&balance(b)>0);const monthEnd=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate();const due= `${month}-${monthEnd}`<=date;
 const pendingMonths = new Set<string>();
 for (const entity of [...data.employees.map(e=>({id:e.id,start:e.joined,kind:'Salary'})),...data.halls.map(h=>({id:h.id,start:h.start,kind:'Rent'}))]) {
   if(entity.kind!==kind)continue;
   let cursor=entity.start.slice(0,7);
   for(let i=0;cursor<date.slice(0,7)&&i<1200;i++) {
     if(!data.bills.some(b=>b.entity===entity.id&&b.kind===entity.kind&&b.month===cursor)) pendingMonths.add(cursor);
     const [y,m]=cursor.split('-').map(Number);cursor=m===12?`${y+1}-01`:`${y}-${String(m+1).padStart(2,'0')}`;
   }
 }
 const renewals=data.halls.filter(h=>h.renewal && Math.ceil((new Date(h.renewal+'T00:00:00').getTime()-new Date(date+'T00:00:00').getTime())/86400000)<=30);
 function exportBackup(){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`aishwarya-staff-rent-${date}.json`;a.click();URL.revokeObjectURL(url);}
 if(!ready)return <main className="adminPage sr"><h1>{title}</h1><p className="adminMessage" role="status">{message}</p><a href="/admin">Admin sign in</a></main>;
 return <main className="adminPage sr"><div className="sr-screen"><header className="adminHeader"><div><p className="kicker">AISHWARYA PARTY HALL · OFFLINE ADMIN</p><h1>{title}</h1><p>{isSalary?'Employees, leave, advances and salary payments':'Hall agreements, rent payments and renewals'} · Padi &amp; Korattur</p></div><a href="/admin">← Admin Home</a></header><div className="sr-notice">Stored only in this browser on this computer. Export backups regularly. Reminders update while this page is open; sending slips requires internet.</div><nav aria-label={`${title} management`}>{tabs.map(t=><button key={t} aria-current={tab===t?'page':undefined} onClick={()=>setTab(t)}>{t}</button>)}</nav><p className="adminMessage" role="status">{message}</p><div className="sr-toolbar"><label>{isSalary?'Salary month':'Rent month'}<input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label><span>{isSalary?'Calendar-day salary basis · salary due at month end':'Monthly hall rent due at month end'}</span></div>
 {tab==='Overview'&&<><section className="sr-cards"><article><span>{isSalary?'Employees':'Hall locations'}</span><strong>{isSalary?data.employees.length:data.halls.length}</strong></article><article><span>Unpaid finalised bills · all months</span><strong>{money(outstanding.reduce((s,b)=>s+balance(b),0))}</strong></article>{isSalary&&<article><span>Advances not assigned to payroll</span><strong>{money(data.employees.reduce((s,e)=>s+advanceBalance(data,e.id),0))}</strong></article>}{!isSalary&&<article><span>Renewals within 30 days / overdue</span><strong>{renewals.length}</strong></article>}</section><section><h2>Monthly calculations</h2>{pendingMonths.size>0&&<div className="sr-notice">Months awaiting review: {[...pendingMonths].sort().map(m=><button key={m} onClick={()=>setMonth(m)}>{m}</button>)}</div>}<p>{due?'Month-end payment reminder: review and finalise the calculations below.':`Preview for this month. Finalise at month end after reviewing ${isSalary?'leave and deductions':'the hall agreement'}.`} {isSalary?'Finalising locks this month’s calculation and reserves its advance recovery once.':'Finalising locks this month’s rent amount.'}</p>{drafts.length===0&&<p>No new calculations. Add {isSalary?'employee':'hall'} details, or view finalised bills in Payments.</p>}{drafts.map(b=><article className="sr-row" key={b.id}><div><b>{b.name}</b><p>{b.location} · {b.kind} · {month}</p>{isSalary?<small>Basic {money(b.basic)} + extras {money(b.extra)} − leave {money(b.leave)} − advance {money(b.recovery)} − debits {money(b.debit)}</small>:<small>Monthly agreement rent {money(b.basic)}</small>}</div><strong>{money(b.total)}</strong><button disabled={!due} onClick={()=>save({...data,bills:[...data.bills,b]})}>Finalise</button></article>)}</section><section><h2>Payment reminders · all months</h2>{outstanding.length===0?<p>No unpaid finalised bills.</p>:outstanding.map(b=><article className="sr-row" key={b.id}><div><b>{b.name}</b><p>{b.month} · {b.location}</p></div><strong>{money(balance(b))} due</strong><button onClick={()=>{setMonth(b.month);setTab('Payments');}}>Record payment</button></article>)}</section>{!isSalary&&<section><h2>Renewal reminders</h2>{renewals.length===0?<p>No upcoming renewals.</p>:renewals.map(h=><p key={h.id}><b>{h.location}</b> · Agreement renewal {h.renewal} · <button onClick={()=>setTab('Hall Details')}>Update renewal date</button></p>)}</section>}</>}
 {tab==='Employees'&&<><section><h2>Add employee</h2><form onSubmit={e=>form(e,f=>save({...data,employees:[...data.employees,{id:uid(),name:str(f,'name'),location:str(f,'location'),phone:str(f,'phone'),role:str(f,'role'),joined:str(f,'joined'),salary:num(f,'salary'),recovery:num(f,'recovery'),paidLeave:num(f,'paidLeave')}]}))}><Field name="name" label="Employee name"/><Location/><Field name="role" label="Job role"/><Field name="phone" label="Phone (country code for WhatsApp)" required={false}/><Field name="joined" label="Joining date" type="date"/><Field name="salary" label="Monthly basic salary ₹" type="number"/><Field name="recovery" label="Monthly advance recovery ₹" type="number" value={0}/><Field name="paidLeave" label="Paid leave allowance / month (days)" type="number" value={0}/><button>Add employee</button></form></section>{data.employees.map(emp=><section key={emp.id}><h2>{emp.name} · {emp.location}</h2><p>{emp.role} · {emp.phone||'No phone'} · Joined {emp.joined} · Unassigned advance {money(advanceBalance(data,emp.id))}</p><div className="sr-actions"><button onClick={()=>setEditingId(emp.id)}>Edit</button><button className="sr-delete" onClick={()=>removeRecord(emp.id,emp.name)}>Delete</button></div>{editingId===emp.id&&<form key={JSON.stringify(emp)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const joined=str(f,'joined');if(data.entries.some(x=>x.employee===emp.id&&x.date<joined)||data.bills.some(b=>b.kind==='Salary'&&b.entity===emp.id&&b.month<joined.slice(0,7))){setMessage('Joining date cannot be after existing ledger entries or salary months.');return;}if(save({...data,employees:data.employees.map(x=>x.id===emp.id?{...x,name:str(f,'name'),location:str(f,'location'),role:str(f,'role'),joined,salary:num(f,'salary'),recovery:num(f,'recovery'),paidLeave:num(f,'paidLeave'),phone:str(f,'phone')}:x)}))setEditingId(null);}}><Field name="name" label="Employee name" value={emp.name}/><Location value={emp.location}/><Field name="role" label="Job role" value={emp.role}/><Field name="joined" label="Joining date" type="date" value={emp.joined}/><Field name="salary" label="Monthly salary ₹ (unfinalised months)" type="number" value={emp.salary}/><Field name="recovery" label="Monthly advance recovery ₹" type="number" value={emp.recovery}/><Field name="paidLeave" label="Paid leave allowance / month (days)" type="number" value={emp.paidLeave}/><Field name="phone" label="Phone" value={emp.phone} required={false}/><p>Changes apply to unfinalised calculations. Existing bills keep their saved details.</p><button>Save changes</button><button type="button" onClick={()=>setEditingId(null)}>Cancel</button></form>}</section>)}</>}
 {tab==='Leave & Ledger'&&<><section><h2>Leave, advances & employee ledger</h2><p>For leave, enter days (0.5 for a half day). For other entries, enter rupees. Debits are salary deductions; reimbursements are money owed to employees.</p><form onSubmit={e=>form(e,f=>{const employee=str(f,'employee'),entryDate=str(f,'date'),kind=str(f,'kind'),amount=num(f,'amount');if(data.bills.some(b=>b.kind==='Salary'&&b.entity===employee&&b.month===entryDate.slice(0,7))){setMessage('This salary month is locked. Choose an unfinalised month.');return false;}if(kind==='Debit'){const employeeData=data.employees.find(x=>x.id===employee);const prior=data.entries.filter(x=>x.employee===employee&&x.kind==='Debit'&&x.date.startsWith(entryDate.slice(0,7))).reduce((s,x)=>s+x.amount,0);if(employeeData&&prior+amount>employeeData.salary){setMessage('Debits exceed monthly salary. Split the deduction across months.');return false;}}if(amount<=0){setMessage('Enter an amount or days greater than zero.');return false;}const selectedEmployee=data.employees.find(x=>x.id===employee);if(selectedEmployee&&entryDate<selectedEmployee.joined){setMessage('Entry date cannot be before joining date.');return false;}if(kind.includes('leave')){const existing=data.entries.filter(x=>x.employee===employee&&x.date===entryDate&&x.kind.includes('leave')).reduce((s,x)=>s+x.amount,0);if(existing+amount>1){setMessage('Total leave cannot exceed one day on a date.');return false;}}return save({...data,entries:[...data.entries,{id:uid(),employee,date:entryDate,kind,amount,note:str(f,'note')}]});})}><label>Employee<select name="employee" required><option value="">Choose employee</option>{data.employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><Field name="date" label="Date" type="date" value={date}/><label>Entry type<select name="kind">{['Advance','Debit','Paid leave','Unpaid leave','Bonus / overtime','Reimbursement'].map(k=><option key={k}>{k}</option>)}</select></label><Field name="amount" label="Amount ₹ / leave days" type="number"/><Field name="note" label="Reason / payment method / reference"/><button>Save entry</button></form></section><section><h2>Ledger · {month}</h2>{data.employees.map(e=><p key={e.id}>{e.name}: Paid leave {data.entries.filter(x=>x.employee===e.id&&x.date.startsWith(month)&&x.kind==='Paid leave').reduce((s,x)=>s+x.amount,0)} / {e.paidLeave} days allowance</p>)}{data.entries.filter(e=>e.date.startsWith(month)).sort((a,b)=>b.date.localeCompare(a.date)).map(e=><article className="sr-row" key={e.id}><div><b>{data.employees.find(x=>x.id===e.employee)?.name} · {e.kind}</b><p>{e.date} · {e.note}</p></div><strong>{e.kind.includes('leave')?`${e.amount} day(s)`:money(e.amount)}</strong></article>)}</section></>}
 {tab==='Hall Details'&&<><section><h2>Add hall agreement</h2><form onSubmit={e=>form(e,f=>{if(data.halls.some(h=>h.location===str(f,'location'))){setMessage('This location already exists. Update its agreement below.');return false;}return save({...data,halls:[...data.halls,{id:uid(),location:str(f,'location'),address:str(f,'address'),owner:str(f,'owner'),phone:str(f,'phone'),rent:num(f,'rent'),deposit:num(f,'deposit'),start:str(f,'start'),renewal:str(f,'renewal')}]});})}><Location/><Field name="address" label="Hall address"/><Field name="owner" label="Owner name"/><Field name="phone" label="Owner phone" required={false}/><Field name="rent" label="Monthly rent ₹" type="number"/><Field name="deposit" label="Deposit ₹" type="number" value={0}/><Field name="start" label="First rent month / agreement start" type="date"/><Field name="renewal" label="Agreement renewal date" type="date"/><button>Add hall</button></form></section>{data.halls.map(h=><section key={h.id}><h2>{h.location}</h2><p>{h.address} · Owner: {h.owner} · {h.phone} · Deposit {money(h.deposit)}</p><div className="sr-actions"><button onClick={()=>setEditingId(h.id)}>Edit</button><button className="sr-delete" onClick={()=>removeRecord(h.id,`${h.location} hall agreement`)}>Delete</button></div>{editingId===h.id&&<form key={JSON.stringify(h)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const location=str(f,'location'),start=str(f,'start'),renewal=str(f,'renewal');if(data.halls.some(x=>x.id!==h.id&&x.location===location)){setMessage('This location already has an agreement.');return;}if(renewal<start){setMessage('Renewal date cannot be before the agreement start.');return;}if(data.bills.some(b=>b.kind==='Rent'&&b.entity===h.id&&b.month<start.slice(0,7))){setMessage('Agreement start cannot be after existing rent months.');return;}if(save({...data,halls:data.halls.map(x=>x.id===h.id?{...x,location,address:str(f,'address'),owner:str(f,'owner'),phone:str(f,'phone'),deposit:num(f,'deposit'),start,rent:num(f,'rent'),renewal}:x)}))setEditingId(null);}}><Location value={h.location}/><Field name="address" label="Hall address" value={h.address}/><Field name="owner" label="Owner name" value={h.owner}/><Field name="phone" label="Owner phone" value={h.phone} required={false}/><Field name="deposit" label="Deposit ₹" type="number" value={h.deposit}/><Field name="start" label="Agreement start" type="date" value={h.start}/><Field name="rent" label="Monthly rent ₹ (unfinalised months)" type="number" value={h.rent}/><Field name="renewal" label="Next renewal date" type="date" value={h.renewal}/><p>Existing rent bills keep their saved details.</p><button>Save changes</button><button type="button" onClick={()=>setEditingId(null)}>Cancel</button></form>}</section>)}</>}
 {tab==='Payments'&&<section><h2>Finalised {isSalary?'salary':'rent'} · {month}</h2><p>Part payments keep reminders open. Full payment closes the reminder automatically.</p>{bills.length===0&&<p>No finalised bills for this month. Review calculations in Overview.</p>}{bills.map(b=><article className="sr-bill" key={b.id}><div className="sr-row"><div><h3>{b.name}</h3><p>{b.location} · {b.month} · {balance(b)===0?'Closed / settled':'Payment due'}</p></div><strong>{money(b.total)} total<br/>{money(balance(b))} due</strong>{b.kind==='Salary'&&<button onClick={()=>setSlip(b)}>Salary slip</button>}</div>{b.payments.map(p=><p key={p.id}>{p.date} · {money(p.amount)} · {p.method} · {p.reference}</p>)}{balance(b)>0&&<form onSubmit={e=>form(e,f=>{const amount=num(f,'amount');if(amount<=0||amount>balance(b)){setMessage('Payment must be positive and no greater than the balance.');return false;}if(str(f,'date')>date){setMessage('Payment date cannot be in the future.');return false;}return save({...data,bills:data.bills.map(x=>x.id===b.id?{...x,payments:[...x.payments,{id:uid(),date:str(f,'date'),amount,method:str(f,'method'),reference:str(f,'reference')}]}:x)});})}><Field name="date" label="Payment date" type="date" value={date}/><Field name="amount" label="Amount paid ₹" type="number"/><label>Method<select name="method"><option>UPI</option><option>Bank transfer</option><option>Cash</option><option>Cheque</option></select></label><Field name="reference" label="Reference / receipt note" required={false}/><button>Record payment</button></form>}</article>)}</section>}
 {tab==='Backup'&&<section><h2>Offline backup</h2><p>This backup includes both Staff Salary and Hall Rent records. It is separate from the main booking database. Export before clearing browser data or moving computers. Backups contain private employee information.</p><button onClick={exportBackup}>Download backup</button><label>Restore staff & rent backup (replaces these records)<input type="file" accept="application/json,.json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text());if(!validRecords(parsed))throw Error();if(!confirm('Replace all staff and rent records with this backup? Download your current backup first.'))return;save(parsed);}catch{setMessage('Invalid backup file. No records changed.');}e.target.value='';}}/></label></section>}
 </div>{slip&&<div className="sr-slip"><div className="sr-screen sr-toolbar"><button onClick={()=>window.print()}>Print / Save PDF</button><button onClick={()=>{const phone=data.employees.find(e=>e.id===slip.entity)?.phone.replace(/\D/g,'')||'';window.open(`https://wa.me/${phone}?text=${encodeURIComponent(`Aishwarya Party Hall — Salary slip\n${slip.name} | ${slip.location} | ${slip.month}\nBasic: ${money(slip.basic)}\nExtras: ${money(slip.extra)}\nLeave: ${money(slip.leave)}\nAdvance recovery: ${money(slip.recovery)}\nOther deductions: ${money(slip.debit)}\nNet salary: ${money(slip.total)}\nPaid: ${money(paid(slip))}\nBalance due: ${money(balance(slip))}`)}`,'_blank','noopener,noreferrer');}}>Share via WhatsApp</button><button onClick={()=>setSlip(null)}>Close slip</button></div><p>AISHWARYA PARTY HALL</p><h1>Salary slip</h1><h2>{slip.name}</h2><p>{slip.location} · {slip.month}</p><dl>{[['Basic salary',slip.basic],['Bonus / overtime / reimbursement',slip.extra],['Unpaid leave deduction',slip.leave],['Advance recovery',slip.recovery],['Other deductions',slip.debit],['Net salary',slip.total],['Amount paid',paid(slip)],['Balance payable',balance(slip)]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{money(Number(v))}</dd></div>)}</dl><p>{balance(slip)===0?'Settled':'Payment pending'} · Generated {date}</p></div>}</main>;
}
