"use client";
import { useState } from "react";
import type { PhotographyContent } from "../lib/photography";
import { photographyWhatsapp } from "../lib/photography-contact";
export type PublicPhotography = PhotographyContent & {id:string;mobile:string;featured:boolean};
export default function PhotographyPortfolio({portfolio:p}:{portfolio:PublicPhotography}) {
 const [hall,setHall]=useState(p.hall==="Both"?"Padi":p.hall);
 const [date,setDate]=useState("");
 return <section className="photoPortfolio"><p className="kicker">{p.category} · {p.hall==="Both"?"Padi & Korattur":p.hall}</p><h1>{p.title}</h1><h2>{p.photographer}</h2><p>{p.description}</p><h3>Services</h3><p>{p.services}</p>{p.included&&<p>{p.included}</p>}<h3>Availability</h3><p>{p.availability||"Enquire directly to confirm your event date."}</p><p>Reference: {p.id}</p><div className="photoSamples">{p.photos.map((src,i)=><a key={src} href={src} target="_blank" rel="noreferrer"><img src={src} alt={`${p.title} — sample ${i+1}`} loading="lazy"/></a>)}</div><div className="decorFilters"><label>Event hall<select value={hall} onChange={e=>setHall(e.target.value)}>{(p.hall==="Both"?["Padi","Korattur"]:[p.hall]).map(h=><option key={h}>{h}</option>)}</select></label><label>Event date (optional)<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><h2>Photography packages</h2><div className="photoPackages">{p.packages.map((pkg,i)=><article className="decorPanel" key={i}><h3>{pkg.name}</h3><p className="photoPrice">{pkg.price===null?"Enquire for pricing":`₹${pkg.price.toLocaleString("en-IN")}`}</p><p>{pkg.hours} hours of coverage</p><p>{pkg.included}</p>{p.mobile&&<a className="maroonButton" href={photographyWhatsapp(p.mobile,p.id,p.title,p.photographer,pkg.name,hall,date)} target="_blank" rel="noreferrer">Enquire about this package →</a>}</article>)}</div><p>Final pricing, coverage and availability are confirmed by the photographer.</p>{p.mobile?<><p>Photographer WhatsApp: +{p.mobile}</p><a className="maroonButton" href={photographyWhatsapp(p.mobile,p.id,p.title,p.photographer,undefined,hall,date)} target="_blank" rel="noreferrer">Contact photographer →</a></>:<p>Contact our hall team for this photographer’s details.</p>}</section>;
}
