/** Saved SS Foods menu-card image links. Add each newly created item photo here. */
export const menuImageLinks: Record<string, string> = {
  "grape juice": "/images/catering/menu/grape-juice.png",
  "orange juice": "/images/catering/menu/orange-juice.png",
  "mango juice": "/images/catering/menu/mango-juice.png",
  "lemon mint": "/images/catering/menu/lemon-mint.png",
  "rose milk": "/images/catering/menu/rose-milk.png",
  "watermelon juice": "/images/catering/menu/watermelon-juice.png",
  "semiya payasam": "/images/catering/menu/semiya-payasam.png",
  "paruppu payasam": "/images/catering/menu/paruppu-payasam.png",
  "gulab jamun": "/images/catering/menu/gulab-jamun.png",
  "mysore pak": "/images/catering/menu/mysore-pak.png",
  "boondi laddu": "/images/catering/menu/boondi-laddu.png",
  "wheat halwa": "/images/catering/menu/wheat-halwa.png",
  "sweet pongal": "/images/catering/menu/sweet-pongal.png",
  "semiya kesari": "/images/catering/menu/semiya-kesari.png",
  "rava kesari": "/images/catering/menu/rava-kesari.png",
  "aval kesari": "/images/catering/menu/aval-kesari.png",
  "pineapple kesari": "/images/catering/menu/pineapple-kesari.png",
  "sweet catalogue": "/images/catering/menu/south-indian-sweets.png",
  "pal payasam": "/images/catering/menu/pal-payasam.png",  "sakkarai pongal": "/images/catering/menu/sakkarai-pongal.png",  "jangiri": "/images/catering/menu/jangiri.png",  "badusha": "/images/catering/menu/badusha.png",  "bread halwa": "/images/catering/menu/bread-halwa.png",  "medu vada": "/images/catering/menu/medu-vada.png",
  "masala vada": "/images/catering/menu/masala-vada.png",
  "keerai vada": "/images/catering/menu/keerai-vada.png",
  "paruppu vada": "/images/catering/menu/paruppu-vada.png",
  "vegetable cutlet": "/images/catering/menu/vegetable-cutlet.png",
  "gobi 65": "/images/catering/menu/gobi-65.png",
  "mushroom 65": "/images/catering/menu/mushroom-65.png",
  "paneer tikka": "/images/catering/menu/paneer-tikka.png",
  "paneer 65": "/images/catering/menu/paneer-65.png",
  "baby corn fry": "/images/catering/menu/baby-corn-fry.png",
  "veg spring roll": "/images/catering/menu/veg-spring-roll.png",
  "cauliflower fry": "/images/catering/menu/cauliflower-fry.png",
  "chilli paneer": "/images/catering/menu/chilli-paneer.png",
  "crispy corn": "/images/catering/menu/crispy-corn.png",
  "veg manchurian": "/images/catering/menu/veg-manchurian.png",
  "vanilla ice cream - 80 ml": "/images/catering/menu/vanilla-ice-cream.png",
  "butterscotch ice cream - 80 - ml": "/images/catering/menu/butterscotch-ice-cream.png",
  "chocolate ice cream - 100 ml": "/images/catering/menu/chocolate-ice-cream.png",
  "kulfi": "/images/catering/menu/kulfi.png",
};
