import { env } from "cloudflare:workers";
import { getStaffSession } from "../../admin-auth";

export type CctvCamera = { id: number; label: string; area: string; customerVisible: boolean };
const defaults: CctvCamera[] = [{ id: 1, label: "Camera 1", area: "Main Hall", customerVisible: true }, { id: 2, label: "Camera 2", area: "Entrance", customerVisible: true }, { id: 3, label: "Camera 3", area: "Dining Area", customerVisible: true }, { id: 4, label: "Camera 4", area: "Parking", customerVisible: true }, { id: 5, label: "Camera 5", area: "Camera 5", customerVisible: false }, { id: 6, label: "Camera 6", area: "Camera 6", customerVisible: false }, { id: 7, label: "Camera 7", area: "Camera 7", customerVisible: false }, { id: 8, label: "Camera 8", area: "Camera 8", customerVisible: false }];
let readyPromise: Promise<void> | null = null;
async function ready() { if (!env.DB) throw new Error("Cloudflare D1 binding `DB` is unavailable."); if (!readyPromise) readyPromise = (async () => { await env.DB.prepare("CREATE TABLE IF NOT EXISTS cctv_camera_settings (camera_id INTEGER PRIMARY KEY, label TEXT NOT NULL, area TEXT NOT NULL, customer_visible INTEGER NOT NULL DEFAULT 0)").run(); await env.DB.batch(defaults.map((camera) => env.DB.prepare("INSERT OR IGNORE INTO cctv_camera_settings (camera_id, label, area, customer_visible) VALUES (?, ?, ?, ?)").bind(camera.id, camera.label, camera.area, camera.customerVisible ? 1 : 0))); })().catch((error) => { readyPromise = null; throw error; }); return readyPromise; }
async function cameras(): Promise<CctvCamera[]> { await ready(); const result = await env.DB.prepare("SELECT camera_id, label, area, customer_visible FROM cctv_camera_settings ORDER BY camera_id").all<{ camera_id: number; label: string; area: string; customer_visible: number }>(); return (result.results ?? []).map((camera) => ({ id: camera.camera_id, label: camera.label, area: camera.area, customerVisible: Boolean(camera.customer_visible) })); }
export async function GET() { try { return Response.json({ cameras: await cameras() }); } catch { return Response.json({ error: "Unable to load camera settings." }, { status: 500 }); } }
export async function POST(request: Request) { if ((await getStaffSession(request))?.role !== "admin") return Response.json({ error: "Administrator access required" }, { status: 403 }); try { const body = await request.json() as { cameras?: CctvCamera[] }; if (!Array.isArray(body.cameras) || body.cameras.length !== 8) return Response.json({ error: "All eight camera settings are required." }, { status: 400 }); await ready(); const updates = body.cameras.map((camera) => { const id = Number(camera.id), label = String(camera.label || "").trim(), area = String(camera.area || "").trim(); if (!Number.isInteger(id) || id < 1 || id > 8 || !label || !area || label.length > 80 || area.length > 120) throw new Error("invalid"); return env.DB.prepare("UPDATE cctv_camera_settings SET label = ?, area = ?, customer_visible = ? WHERE camera_id = ?").bind(label, area, camera.customerVisible ? 1 : 0, id); }); await env.DB.batch(updates); return Response.json({ ok: true, cameras: await cameras() }); } catch { return Response.json({ error: "Enter a name and area for every camera." }, { status: 400 }); } }
