import { sql } from "drizzle-orm";
import { getDb } from "../../../db";
import { getStaffSession } from "../../admin-auth";

export type CctvCamera = { id: number; label: string; area: string; customerVisible: boolean };
const defaults: CctvCamera[] = [{id:1,label:"Camera 1",area:"Main Hall",customerVisible:true},{id:2,label:"Camera 2",area:"Entrance",customerVisible:true},{id:3,label:"Camera 3",area:"Dining Area",customerVisible:true},{id:4,label:"Camera 4",area:"Parking",customerVisible:true},{id:5,label:"Camera 5",area:"Camera 5",customerVisible:false},{id:6,label:"Camera 6",area:"Camera 6",customerVisible:false},{id:7,label:"Camera 7",area:"Camera 7",customerVisible:false},{id:8,label:"Camera 8",area:"Camera 8",customerVisible:false}];

async function ready() { const db=getDb(); await db.execute(sql`CREATE TABLE IF NOT EXISTS cctv_camera_settings (camera_id INT PRIMARY KEY, label VARCHAR(80) NOT NULL, area VARCHAR(120) NOT NULL, customer_visible TINYINT(1) NOT NULL DEFAULT 0)`); for (const camera of defaults) await db.execute(sql`INSERT IGNORE INTO cctv_camera_settings (camera_id,label,area,customer_visible) VALUES (${camera.id},${camera.label},${camera.area},${camera.customerVisible?1:0})`); }
async function cameras(): Promise<CctvCamera[]> { await ready(); const result=await getDb().execute(sql`SELECT camera_id AS id,label,area,customer_visible AS customerVisible FROM cctv_camera_settings ORDER BY camera_id`); return ((result[0]??[]) as unknown as Array<CctvCamera & {customerVisible:number|boolean}>).map((camera)=>({...camera,customerVisible:Boolean(camera.customerVisible)})); }
export async function GET(){try{return Response.json({cameras:await cameras()});}catch{return Response.json({error:"Unable to load camera settings."},{status:500});}}
export async function POST(request:Request){if((await getStaffSession(request))?.role!=="admin")return Response.json({error:"Administrator access required"},{status:403});try{const body=await request.json() as {cameras?:CctvCamera[]};if(!Array.isArray(body.cameras)||body.cameras.length!==8)return Response.json({error:"All eight camera settings are required."},{status:400});await ready();for(const camera of body.cameras){const id=Number(camera.id),label=String(camera.label||"").trim(),area=String(camera.area||"").trim();if(!Number.isInteger(id)||id<1||id>8||!label||!area||label.length>80||area.length>120)return Response.json({error:"Enter a name and area for every camera."},{status:400});await getDb().execute(sql`UPDATE cctv_camera_settings SET label=${label}, area=${area}, customer_visible=${camera.customerVisible?1:0} WHERE camera_id=${id}`);}return Response.json({ok:true,cameras:await cameras()});}catch{return Response.json({error:"Unable to save camera settings."},{status:500});}}
